spring:
  application:
    name: ecomapp-category-service
  threads:
    virtual:
      enabled: true
  data: #MongoDB Server Configuration
    mongodb:
      host: localhost
      port: 27017
      username: mongo
      password: mongo
      database: myDB
      authentication-database: admin
server:
  port: 8083


## JWT Security Secret
#security:
#  jwt:
#    secret-key: springsecurityjwtsecret
#    token-duration: 1D

# Eureka Client
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${REGISTRY_SERVER_HOST:localhost}:8761/eureka
    registerWithEureka: true
    fetchRegistry: true